AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "stripe implementation in aws lambda"
Globals:
  Function:
    Timeout: 120
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  stripeCheckSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: stripeCheckSessionFunction
      Handler: app.stripeCheckSession
      Runtime: nodejs20.x
      Environment:
        Variables:
          publishable_key: "pk_test_51P9KqvIjAnNUwiA8MUYrEcyjq9mheRP4Hk6cHqv2HiGrklCIPWIkJtFJ7kjuV6npMbbbnm4oYaY03b7eu81vohFq00YejX9g5B"
          secret_key: "sk_test_51P9KqvIjAnNUwiA88oIusMbgnsGkmFLtPA1RoE9UuFgvo9PKGr5W6AVxBiYwS2me6xrNhP55JJyvZBjr3L1jM2TI00kKX5YCvP"
      Events:
        stripeCheckSessionEvent:
          Type: Api
          Properties:
            Path: /api/payment/checkout-session
            Method: post
    Metadata:
      SamResourceId: stripeCheckSessionFunction


  productPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: productPageFunction
      Handler: app.productPage
      Runtime: nodejs20.x
      Environment:
        Variables:
          publishable_key: "pk_test_51P9KqvIjAnNUwiA8MUYrEcyjq9mheRP4Hk6cHqv2HiGrklCIPWIkJtFJ7kjuV6npMbbbnm4oYaY03b7eu81vohFq00YejX9g5B"
          secret_key: "sk_test_51P9KqvIjAnNUwiA88oIusMbgnsGkmFLtPA1RoE9UuFgvo9PKGr5W6AVxBiYwS2me6xrNhP55JJyvZBjr3L1jM2TI00kKX5YCvP"
      Events:
        stripeCheckSessionEvent:
          Type: Api
          Properties:
            Path: /api/payment/product
            Method: get
    Metadata:
      SamResourceId: productPageFunction
