AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "stripe implementation in aws lambda"
Globals:
  Function:
    Timeout: 120
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:

  stripeCheckSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: stripeCheckSessionFunction
      Handler: app.checkoutSessionHandler
      Runtime: nodejs20.x
      Environment:
        Variables:
          publishable_key: ""
          secret_key: ""
      Events:
        stripeCheckSessionEvent:
          Type: Api
          Properties:
            Path: /api/payment/checkout-session
            Method: post
    Metadata:
      SamResourceId: stripeCheckSessionFunction


  productPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: productPageFunction
      Handler: app.productPage
      Runtime: nodejs20.x
      Environment:
        Variables:
          publishable_key: ""
          secret_key: ""
      Events:
        stripeCheckSessionEvent:
          Type: Api
          Properties:
            Path: /api/payment/product
            Method: get
    Metadata:
      SamResourceId: productPageFunction



  completePaymentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: completePaymentFunction
      Handler: app.completePayment
      Runtime: nodejs20.x
      Environment:
        Variables:
          publishable_key: ""
          secret_key: ""
      Events:
        completePaymentEvent:
          Type: Api
          Properties:
            Path: /api/payment/complete
            Method: get
    Metadata:
      SamResourceId: completePaymentFunction
